# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-13 16:52
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='department',
            name='company',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='departments', to='organization.Company', verbose_name='所属公司'),
        ),
        migrations.AlterField(
            model_name='staff',
            name='avatar',
            field=models.ImageField(blank=True, default=None, null=True, upload_to='adminlte/user_avatar'),
        ),
        migrations.AlterField(
            model_name='staff',
            name='sex',
            field=models.CharField(choices=[('male', '男'), ('female', '女')], max_length=10, verbose_name='性别'),
        ),
    ]
