# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-13 16:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminlte', '0002_auto_20151224_1007'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menu',
            name='icon',
            field=models.CharField(default='fa-circle-o', help_text='参考:http://fontawesome.io', max_length=50, verbose_name='菜单图标'),
        ),
    ]
