# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-13 16:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('messageset', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='title',
            field=models.CharField(blank=True, default='', max_length=200, null=True, verbose_name='标题'),
        ),
    ]
